### ISSUE TITLE
Should this work the same way with Nativewind

### ISSUE THREAD

**Issue by scott-harrison** [JavierM42/tailwind-mode-aware-colors#5]
I really want to use this with my nativewind project. However not sure if it works or not. It just seems to default to light and doesn't switch mode when the appearance changes.

**Comment by scott-harrison** [comment]
Here is my tailwind config

```js
module.exports = require('tailwind-mode-aware-colors')({
  content: [
   'src/**/*.{js,jsx,ts,tsx}'
  ],
  important: 'html',
  darkMode: 'class',
  theme: {
    extends: {
      primary: {
        light: '#ffffff',
        dark: '#000000',
      }
    }
  },
  plugins: [],
});
```



When looking deeper into the outputted css im seeing
```css
html {
  --color-primary: 255 255 255;
}
```
but nothing else, this is not what i was expecting. I thought i would see 
```css
html .dark {
  --color-primary: 0 0 0;
}
```

Any idea why it wouldn't compile .dark variables?
